"""
Referral note PDF generation (reportlab). Produces a printable, reviewer-
signed referral note for handoff to a higher facility - one of the
"expected features" in the problem statement.
"""

import io
from xml.sax.saxutils import escape as _xml_escape

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from . import risk_rules


def _safe(text):
    """Escape free text before handing it to reportlab's Paragraph(), which parses its input as
    a small XML/HTML-like markup dialect rather than plain text. Real, confirmed bug fixed here:
    an unescaped '<' not immediately followed by a matching closing tag (very plausible in
    ordinary reviewer shorthand, e.g. "BP normal, improving<discharge planned", or in AI-
    generated/patient-reported free text) raised an uncaught ValueError from reportlab's parser,
    which had no try/except around it in app.py's referral-PDF route - a hard Flask 500 for the
    reviewer trying to hand off a case. Every field below that isn't a fixed string this module
    wrote itself is escaped before use; deliberate markup we add ourselves (the "&bull;" entity,
    reviewer notes' "<br/>" line breaks) is added AFTER escaping the underlying text so it is
    never itself escaped away.
    """
    return _xml_escape(str(text) if text is not None else "")


def build_referral_pdf(patient, structured, reviewer_name=None, reviewer_notes=None, referral_facility=None,
                        ai_summary=None, ai_summary_model=None):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=16)
    h2 = styles["Heading2"]
    body = styles["BodyText"]
    small = ParagraphStyle("Small", parent=styles["BodyText"], fontSize=8, textColor=colors.grey)

    tier_meta = risk_rules.RISK_TIER_LABELS.get(structured["risk_tier"], {})
    story = []

    story.append(Paragraph("Referral / Triage Handoff Note", title_style))
    story.append(Paragraph("Educational prototype output - advisory only, not a diagnosis", small))
    story.append(Spacer(1, 8))

    info_table_data = [
        ["Triage ID", patient["triage_id"], "Risk Priority", tier_meta.get("label", structured["risk_tier"])],
        ["Facility", patient.get("facility_name") or "-", "Facility type", patient.get("facility_type") or "-"],
        ["Patient (as provided)", patient.get("display_name") or "(not provided)", "Age / Sex",
         f"{patient.get('age') or 'unknown'} / {patient.get('sex') or 'unknown'}"],
        ["Referring to", referral_facility or "(not specified)", "Reviewer", reviewer_name or "(unsigned)"],
    ]
    t = Table(info_table_data, colWidths=[95, 145, 95, 145])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
        ("BACKGROUND", (2, 0), (2, -1), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(t)
    story.append(Spacer(1, 12))

    if ai_summary:
        story.append(Paragraph("AI-Generated Summary (draft - local model, verify against details below)", h2))
        story.append(Paragraph(_safe(ai_summary), body))
        story.append(Paragraph(f"Generated by: {_safe(ai_summary_model or 'local model')}", small))
        story.append(Spacer(1, 8))

    story.append(Paragraph("Chief Complaint", h2))
    story.append(Paragraph(_safe(structured["chief_complaint"]), body))
    story.append(Spacer(1, 6))

    story.append(Paragraph("Risk Assessment Reasons (system-generated, reviewer-confirmed)", h2))
    for r in structured["risk_reasons"]:
        story.append(Paragraph(f"&bull; {_safe(r)}", body))
    story.append(Spacer(1, 6))

    if structured["symptoms"]:
        story.append(Paragraph("Reported Symptoms", h2))
        for s in structured["symptoms"]:
            story.append(Paragraph(f"&bull; {_safe(s['canonical'].replace('_', ' '))} ({_safe(s['category'])})", body))
        story.append(Spacer(1, 6))

    if structured["vitals"]:
        story.append(Paragraph("Vitals", h2))
        for k, v in structured["vitals"].items():
            story.append(Paragraph(f"&bull; {_safe(k.replace('_', ' '))}: {_safe(v)}", body))
        story.append(Spacer(1, 6))

    if structured["missing_info"]:
        story.append(Paragraph("Missing Information at Time of Referral", h2))
        for m in structured["missing_info"]:
            story.append(Paragraph(f"&bull; {_safe(m)}", body))
        story.append(Spacer(1, 6))

    if reviewer_notes:
        story.append(Paragraph("Reviewer Notes", h2))
        # Escape the raw text FIRST, then add our own deliberate <br/> line breaks - otherwise
        # escaping afterward would turn our own markup into visible "&lt;br/&gt;" text.
        story.append(Paragraph(_safe(reviewer_notes).replace("\n", "<br/>"), body))
        story.append(Spacer(1, 6))

    story.append(Spacer(1, 10))
    story.append(Paragraph(
        "DISCLAIMER: Generated by an educational triage-support prototype. Non-diagnostic. "
        "Does not prescribe treatment. For use by qualified health personnel only, alongside "
        "independent clinical judgement.",
        small,
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer
