"""
Assembles the final structured-note dict and a plain-text rendering used
for the reviewer detail page and referral export.

This is deliberately template/rules-based (no external LLM call) so the
prototype runs fully offline and deterministically. The interface here
(`build_note_text`) is where a real deployment could instead call an LLM
to produce a more fluent summary from the same structured fields -
without changing anything upstream.
"""

from . import risk_rules


def build_note_text(patient, structured, ocr_text=None, ai_summary=None):
    tier_label = risk_rules.RISK_TIER_LABELS.get(structured["risk_tier"], {}).get("label", structured["risk_tier"])
    lines = []
    lines.append(f"TRIAGE NOTE - {patient['triage_id']}")
    lines.append(f"Facility: {patient.get('facility_name') or '-'} ({patient.get('facility_type')})")
    lines.append(f"Patient: {patient.get('display_name') or '(not provided)'}  Age: {patient.get('age') or 'unknown'}  Sex: {patient.get('sex') or 'unknown'}")
    lines.append(f"Preferred language: {patient.get('preferred_language')}")
    lines.append("")
    if ai_summary:
        lines.append("AI-GENERATED SUMMARY (draft, local model - verify against structured fields below):")
        lines.append(f"  {ai_summary}")
        lines.append("")
    lines.append(f"RISK PRIORITY: {tier_label}  (score: {structured['risk_score']})")
    lines.append("Reasons:")
    for r in structured["risk_reasons"]:
        lines.append(f"  - {r}")
    lines.append("")
    lines.append(f"Chief complaint: {structured['chief_complaint']}")
    lines.append("")
    if structured["symptoms"]:
        lines.append("Reported symptoms:")
        for s in structured["symptoms"]:
            sev = {0: "unspecified", 1: "mild", 2: "moderate", 3: "severe", 4: "extreme"}.get(s["severity_level"], "unspecified")
            lines.append(f"  - {s['canonical'].replace('_', ' ')} (severity: {sev}, category: {s['category']})")
    if structured.get("negated_symptoms"):
        # negated_symptoms is stored as canonical keys (e.g. "chest_pain") so translation lookups
        # elsewhere work - humanize with spaces here since this is a plain-text rendering.
        denied = ", ".join(n.replace("_", " ") for n in structured["negated_symptoms"])
        lines.append(f"Explicitly denied by patient: {denied}")
    lines.append("")
    if structured["timeline"]:
        lines.append("Timeline (heuristic, reviewer should confirm):")
        for e in structured["timeline"]:
            lines.append(f"  - {e['symptom']}: {e['onset_text']}")
    lines.append("")
    if structured["vitals"]:
        lines.append("Recorded / extracted vitals:")
        for k, v in structured["vitals"].items():
            lines.append(f"  - {k.replace('_', ' ')}: {v}")
    else:
        lines.append("Vitals: none recorded")
    lines.append("")
    if structured["missing_info"]:
        lines.append("Missing information:")
        for m in structured["missing_info"]:
            lines.append(f"  - {m}")
    lines.append("")
    if structured["follow_up_questions"]:
        lines.append("Suggested follow-up questions for health worker / reviewer:")
        for q in structured["follow_up_questions"]:
            lines.append(f"  - {q}")
    if ocr_text:
        lines.append("")
        lines.append("OCR-extracted text from uploaded report (verify against original):")
        lines.append(ocr_text.strip())
    lines.append("")
    lines.append("---")
    lines.append("DISCLAIMER: This note is generated by an educational prototype for")
    lines.append("triage-support purposes only. It is NON-DIAGNOSTIC, does not prescribe")
    lines.append("treatment, and must be reviewed by a qualified health worker, nurse,")
    lines.append("doctor, or medical officer before any clinical action is taken.")
    return "\n".join(lines)
