"""
Lightweight, fully-offline translation layer for English / Hindi / Odia.

IMPORTANT SCOPE NOTE (documented deliberately, not hidden): this is a
dictionary/phrase-substitution translator covering common triage
vocabulary (UI labels, the fixed follow-up question bank, and known
symptom terms) - NOT a general machine-translation system. It exists so
the prototype can demonstrate multilingual accessibility end-to-end
without requiring internet access or a paid translation API. A production
deployment should swap this module for a proper MT/LLM translation
service behind the same `get_ui_string()` / `translate_note_summary()`
interface.

ODIA ACCURACY NOTE: the Odia phrases below were written from general
language knowledge, not verified against a live Odia speaker or a
dictionary lookup at build time. They use standard, common vocabulary
(the kind found in everyday Odia health communication) and should be
substantially correct, but - precisely BECAUSE this is a healthcare tool -
they should still be spot-checked by a native Odia speaker before any
real (non-demo) use. That review is a small, one-time task: everything
needing checking lives in the three dictionaries below, keyed by the
same English source string, so a reviewer can go phrase-by-phrase without
touching any code logic.
"""

SUPPORTED_LANGUAGES = {
    "en": "English",
    "hi": "Hindi (हिन्दी)",
    "or": "Odia (ଓଡ଼ିଆ)",
}

# UI chrome strings used across templates
UI_STRINGS = {
    "app_title": {
        "en": "Healthcare Triage Assistant", "hi": "स्वास्थ्य ट्रायज सहायक",
        "or": "ସ୍ୱାସ୍ଥ୍ୟ ଟ୍ରାଏଜ୍ ସହାୟକ",
    },
    "consent_title": {
        "en": "Consent to Continue", "hi": "आगे बढ़ने हेतु सहमति",
        "or": "ଆଗକୁ ବଢ଼ିବା ପାଇଁ ସମ୍ମତି",
    },
    "chief_complaint": {"en": "Chief Complaint", "hi": "मुख्य शिकायत", "or": "ମୁଖ୍ୟ ଅଭିଯୋଗ"},
    "risk_priority": {"en": "Risk Priority", "hi": "जोखिम प्राथमिकता", "or": "ବିପଦ ଅଗ୍ରାଧିକାର"},
    "follow_up_questions": {
        "en": "Follow-up Questions for Reviewer", "hi": "समीक्षक के लिए अनुवर्ती प्रश्न",
        "or": "ସମୀକ୍ଷକଙ୍କ ପାଇଁ ଅନୁବର୍ତ୍ତୀ ପ୍ରଶ୍ନ",
    },
    "missing_info": {"en": "Missing Information", "hi": "अनुपस्थित जानकारी", "or": "ଅନୁପସ୍ଥିତ ସୂଚନା"},
    "disclaimer": {
        "en": "This tool organises information for a qualified reviewer. It does NOT diagnose or prescribe treatment.",
        "hi": "यह उपकरण योग्य समीक्षक के लिए जानकारी व्यवस्थित करता है। यह निदान या उपचार नहीं देता।",
        "or": "ଏହି ଉପକରଣ ଯୋଗ୍ୟ ସମୀକ୍ଷକଙ୍କ ପାଇଁ ସୂଚନା ସଜାଡ଼େ। ଏହା ରୋଗ ନିର୍ଣ୍ଣୟ କିମ୍ବା ଚିକିତ୍ସା ପରାମର୍ଶ ଦିଏ ନାହିଁ।",
    },

    # ---- Added: triage_detail.html coverage gap (real, confirmed bug) ----
    # Everything below was previously hardcoded English directly in triage_detail.html - only
    # chief_complaint/risk_priority/missing_info/follow_up_questions (above) were ever wired to
    # this phrase bank, so switching the language switcher to Hindi/Odia left the vast majority
    # of the reviewer detail page (every section heading, button, and static label) in English
    # regardless of the selected language. See README §11.13.
    "patient_anonymised_view": {"en": "Patient (anonymised view)", "hi": "रोगी (गुमनाम दृश्य)", "or": "ରୋଗୀ (ପରିଚୟ ଗୋପନ ଦୃଶ୍ୟ)"},
    "facility_label": {"en": "Facility", "hi": "सुविधा केंद्र", "or": "ସୁବିଧା କେନ୍ଦ୍ର"},
    "scenario_label": {"en": "Scenario", "hi": "परिदृश्य", "or": "ପରିସ୍ଥିତି"},
    "status_label": {"en": "Status", "hi": "स्थिति", "or": "ଅବସ୍ଥା"},
    "input_mode_label": {"en": "Input mode", "hi": "इनपुट प्रकार", "or": "ଇନପୁଟ୍ ପ୍ରକାର"},
    "name_label": {"en": "Name", "hi": "नाम", "or": "ନାମ"},
    "age_label": {"en": "Age", "hi": "आयु", "or": "ବୟସ"},
    "sex_label": {"en": "Sex", "hi": "लिंग", "or": "ଲିଙ୍ଗ"},
    "unknown_value": {"en": "unknown", "hi": "अज्ञात", "or": "ଅଜଣା"},
    "na_value": {"en": "n/a", "hi": "लागू नहीं", "or": "ପ୍ରଯୁଜ୍ୟ ନୁହେଁ"},
    "preferred_language_label": {"en": "Preferred language", "hi": "पसंदीदा भाषा", "or": "ପସନ୍ଦିତ ଭାଷା"},
    "ai_generated_summary": {"en": "AI-Generated Summary", "hi": "एआई-जनित सारांश", "or": "AI-ଜନିତ ସାରାଂଶ"},
    "ai_summary_draft_note": {
        "en": "(local, offline model - draft only)", "hi": "(स्थानीय, ऑफ़लाइन मॉडल - केवल मसौदा)",
        "or": "(ସ୍ଥାନୀୟ, ଅଫଲାଇନ୍ ମଡେଲ - କେବଳ ଡ୍ରାଫ୍ଟ)",
    },
    "generate_ai_summary": {"en": "Generate AI Summary", "hi": "एआई सारांश बनाएं", "or": "AI ସାରାଂଶ ତିଆରି କରନ୍ତୁ"},
    "regenerate_ai_summary": {"en": "Regenerate AI Summary", "hi": "एआई सारांश पुनः बनाएं", "or": "AI ସାରାଂଶ ପୁନଃ ତିଆରି କରନ୍ତୁ"},
    "ai_summary_meta_generated_by": {"en": "Generated by", "hi": "द्वारा जनित", "or": "ଦ୍ୱାରା ଜନିତ"},
    "ai_summary_meta_at": {"en": "at", "hi": "समय", "or": "ସମୟ"},
    "ai_summary_meta_disclaimer": {
        "en": "This is a rephrasing of the structured data below for readability only - it does not add new findings and never determines the risk priority. Always verify against the structured fields and raw text.",
        "hi": "यह नीचे दिए गए संरचित डेटा का केवल पठनीयता हेतु पुनः लेखन है - यह कोई नया निष्कर्ष नहीं जोड़ता और जोखिम प्राथमिकता कभी तय नहीं करता। हमेशा संरचित फ़ील्ड और मूल पाठ से पुष्टि करें।",
        "or": "ଏହା ତଳେ ଥିବା ସଂଗଠିତ ତଥ୍ୟର କେବଳ ପଠନୀୟତା ପାଇଁ ପୁନଃ ଲିଖନ - ଏହା କୌଣସି ନୂଆ ଫଳାଫଳ ଯୋଡ଼େ ନାହିଁ ଏବଂ ବିପଦ ଅଗ୍ରାଧିକାର କେବେ ନିର୍ଣ୍ଣୟ କରେ ନାହିଁ। ସର୍ବଦା ସଂଗଠିତ ଫିଲ୍ଡ ଏବଂ ମୂଳ ପାଠ୍ୟ ସହିତ ଯାଞ୍ଚ କରନ୍ତୁ।",
    },
    "reported_symptoms": {"en": "Reported Symptoms", "hi": "बताए गए लक्षण", "or": "ଜଣାଇଥିବା ଲକ୍ଷଣ"},
    "category_label": {"en": "category", "hi": "श्रेणी", "or": "ବର୍ଗ"},
    "severity_level_label": {"en": "severity level", "hi": "गंभीरता स्तर", "or": "ଗୁରୁତ୍ୱ ସ୍ତର"},
    "no_symptoms_detected": {
        "en": "No structured symptoms auto-detected - see raw notes.",
        "hi": "कोई संरचित लक्षण स्वतः पहचाना नहीं गया - कच्चे नोट्स देखें।",
        "or": "କୌଣସି ସଂଗଠିତ ଲକ୍ଷଣ ସ୍ୱୟଂଚାଳିତ ଭାବେ ଚିହ୍ନଟ ହୋଇନାହିଁ - କଞ୍ଚା ଟିପ୍ପଣୀ ଦେଖନ୍ତୁ।",
    },
    "explicitly_denied": {"en": "Explicitly Denied by Patient", "hi": "रोगी द्वारा स्पष्ट रूप से नकारा गया", "or": "ରୋଗୀ ଦ୍ୱାରା ସ୍ପଷ୍ଟ ଭାବେ ଅସ୍ୱୀକୃତ"},
    "timeline_heuristic": {"en": "Timeline (heuristic)", "hi": "समयरेखा (अनुमानित)", "or": "ସମୟସୀମା (ଆକଳନ)"},
    "no_timeline_inferred": {
        "en": "No timeline could be inferred.", "hi": "कोई समयरेखा नहीं निकाली जा सकी।",
        "or": "କୌଣସି ସମୟସୀମା ଆକଳନ କରାଯାଇପାରିଲା ନାହିଁ।",
    },
    "vitals_label": {"en": "Vitals", "hi": "जीवन-लक्षण (वाइटल्स)", "or": "ଜୀବନ-ଲକ୍ଷଣ (ଭାଇଟାଲ)"},
    "no_vitals_recorded": {
        "en": "No vitals recorded or extracted.", "hi": "कोई जीवन-लक्षण दर्ज या निकाले नहीं गए।",
        "or": "କୌଣସି ଜୀବନ-ଲକ୍ଷଣ ଲିପିବଦ୍ଧ କିମ୍ବା ବାହାର କରାଯାଇ ନାହିଁ।",
    },
    "none_flagged": {"en": "None flagged.", "hi": "कुछ भी चिह्नित नहीं।", "or": "କିଛି ଚିହ୍ନିତ ହୋଇନାହିଁ।"},
    "raw_patient_text": {"en": "Raw patient-reported text", "hi": "रोगी द्वारा दिया गया मूल पाठ", "or": "ରୋଗୀ ଦେଇଥିବା ମୂଳ ପାଠ୍ୟ"},
    "none_provided_see_report": {
        "en": "(none provided - see uploaded report)", "hi": "(कुछ नहीं दिया गया - अपलोड की गई रिपोर्ट देखें)",
        "or": "(କିଛି ଦିଆଯାଇ ନାହିଁ - ଅପଲୋଡ୍ ହୋଇଥିବା ରିପୋର୍ଟ ଦେଖନ୍ତୁ)",
    },
    "ocr_extracted_text_label": {
        "en": "OCR-extracted text from uploaded report", "hi": "अपलोड की गई रिपोर्ट से OCR द्वारा निकाला गया पाठ",
        "or": "ଅପଲୋଡ୍ ହୋଇଥିବା ରିପୋର୍ଟରୁ OCR ଦ୍ୱାରା ବାହାର କରାଯାଇଥିବା ପାଠ୍ୟ",
    },
    "ocr_verify_note": {
        "en": "Always verify OCR output against the original document image before acting on it.",
        "hi": "कार्रवाई करने से पहले हमेशा OCR परिणाम की मूल दस्तावेज़ छवि से पुष्टि करें।",
        "or": "କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ପୂର୍ବରୁ ସର୍ବଦା OCR ଫଳାଫଳକୁ ମୂଳ ଡକ୍ୟୁମେଣ୍ଟ ଛବି ସହିତ ଯାଞ୍ଚ କରନ୍ତୁ।",
    },
    "ai_image_description": {"en": "AI Image Description", "hi": "एआई छवि विवरण", "or": "AI ଛବି ବର୍ଣ୍ଣନା"},
    "ai_image_description_note": {
        "en": "(local vision model - descriptive only, non-diagnostic)",
        "hi": "(स्थानीय विज़न मॉडल - केवल वर्णनात्मक, गैर-निदानात्मक)",
        "or": "(ସ୍ଥାନୀୟ ଭିଜନ ମଡେଲ - କେବଳ ବର୍ଣ୍ଣନାତ୍ମକ, ରୋଗ ନିର୍ଣ୍ଣୟ ନୁହେଁ)",
    },
    "ai_image_meta_disclaimer": {
        "en": "Describes only visible characteristics for your own visual assessment - it does not identify a condition. Always inspect the original photo.",
        "hi": "यह केवल आपके अपने दृश्य आकलन हेतु दिखने वाली विशेषताओं का वर्णन करता है - यह कोई स्थिति पहचानता नहीं है। हमेशा मूल तस्वीर देखें।",
        "or": "ଏହା କେବଳ ଆପଣଙ୍କ ନିଜ ଦୃଶ୍ୟ ମୂଲ୍ୟାୟନ ପାଇଁ ଦୃଶ୍ୟମାନ ବିଶେଷତା ବର୍ଣ୍ଣନା କରେ - ଏହା କୌଣସି ଅବସ୍ଥା ଚିହ୍ନଟ କରେ ନାହିଁ। ସର୍ବଦା ମୂଳ ଫଟୋ ନିରୀକ୍ଷଣ କରନ୍ତୁ।",
    },
    "ai_findings_label": {"en": "AI-Suggested Possible Findings", "hi": "एआई-सुझाए गए संभावित निष्कर्ष", "or": "AI-ପରାମର୍ଶିତ ସମ୍ଭାବ୍ୟ ଫଳାଫଳ"},
    "ai_findings_note": {
        "en": "(MedGemma - for clinician confirmation only)", "hi": "(MedGemma - केवल चिकित्सक की पुष्टि हेतु)",
        "or": "(MedGemma - କେବଳ ଚିକିତ୍ସକଙ୍କ ନିଶ୍ଚିତକରଣ ପାଇଁ)",
    },
    "ai_findings_meta_disclaimer": {
        "en": "Generated from the uploaded photo only, with no access to labs, vitals, or exam findings. Always confirm by direct clinical examination before acting.",
        "hi": "यह केवल अपलोड की गई तस्वीर से जनित है, जिसमें लैब, वाइटल्स या जांच निष्कर्षों तक कोई पहुंच नहीं है। कार्रवाई से पहले हमेशा प्रत्यक्ष नैदानिक परीक्षण से पुष्टि करें।",
        "or": "ଏହା କେବଳ ଅପଲୋଡ୍ ହୋଇଥିବା ଫଟୋରୁ ଜନିତ, ଯେଉଁଥିରେ ଲାବ୍, ଭାଇଟାଲ କିମ୍ବା ପରୀକ୍ଷା ଫଳାଫଳ ପାଇଁ କୌଣସି ପ୍ରବେଶ ନାହିଁ। କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ପୂର୍ବରୁ ସର୍ବଦା ପ୍ରତ୍ୟକ୍ଷ କ୍ଲିନିକାଲ ପରୀକ୍ଷଣ ଦ୍ୱାରା ନିଶ୍ଚିତ କରନ୍ତୁ।",
    },
    "reviewer_actions": {"en": "Reviewer Actions", "hi": "समीक्षक कार्य", "or": "ସମୀକ୍ଷକ କାର୍ଯ୍ୟ"},
    "referral_facility_label": {"en": "Referral facility (if applicable)", "hi": "रेफरल सुविधा केंद्र (यदि लागू हो)", "or": "ରେଫରାଲ ସୁବିଧା କେନ୍ଦ୍ର (ଯଦି ପ୍ରଯୁଜ୍ୟ)"},
    "referral_facility_placeholder": {"en": "e.g. District Hospital, Bhubaneswar", "hi": "जैसे, जिला अस्पताल, भुवनेश्वर", "or": "ଯଥା, ଜିଲ୍ଲା ଡାକ୍ତରଖାନା, ଭୁବନେଶ୍ୱର"},
    "reviewer_notes_label": {"en": "Reviewer notes", "hi": "समीक्षक टिप्पणी", "or": "ସମୀକ୍ଷକ ଟିପ୍ପଣୀ"},
    "reviewer_notes_placeholder": {
        "en": "Clinical impression, actions taken, handoff notes...",
        "hi": "नैदानिक आकलन, की गई कार्रवाई, हैंडओवर नोट्स...",
        "or": "କ୍ଲିନିକାଲ ମତାମତ, ନିଆଯାଇଥିବା ପଦକ୍ଷେପ, ହସ୍ତାନ୍ତର ଟିପ୍ପଣୀ...",
    },
    "next_followup_label": {"en": "Next follow-up / check-in date (optional)", "hi": "अगली अनुवर्ती / जांच तिथि (वैकल्पिक)", "or": "ପରବର୍ତ୍ତୀ ଅନୁବର୍ତ୍ତୀ / ଯାଞ୍ଚ ତାରିଖ (ଐଚ୍ଛିକ)"},
    "next_followup_hint": {
        "en": "For maternal-health follow-up or chronic disease check-in cases - appears on the dashboard until marked complete.",
        "hi": "मातृ-स्वास्थ्य अनुवर्ती या दीर्घकालिक रोग जांच मामलों के लिए - जब तक पूर्ण के रूप में चिह्नित न हो, डैशबोर्ड पर दिखाई देता है।",
        "or": "ମାତୃ-ସ୍ୱାସ୍ଥ୍ୟ ଅନୁବର୍ତ୍ତୀ କିମ୍ବା ଦୀର୍ଘସ୍ଥାୟୀ ରୋଗ ଯାଞ୍ଚ ମାମଲା ପାଇଁ - ସମ୍ପୂର୍ଣ୍ଣ ବୋଲି ଚିହ୍ନିତ ନହେବା ପର୍ଯ୍ୟନ୍ତ ଡ୍ୟାସବୋର୍ଡରେ ଦେଖାଯାଏ।",
    },
    "save_review": {"en": "Save Review", "hi": "समीक्षा सहेजें", "or": "ସମୀକ୍ଷା ସେଭ୍ କରନ୍ତୁ"},
    "download_referral_pdf": {"en": "Download Referral PDF", "hi": "रेफरल पीडीएफ डाउनलोड करें", "or": "ରେଫରାଲ PDF ଡାଉନଲୋଡ୍ କରନ୍ତୁ"},
    "mark_followup_complete_prefix": {"en": "Mark follow-up", "hi": "अनुवर्ती को चिह्नित करें", "or": "ଅନୁବର୍ତ୍ତୀକୁ ଚିହ୍ନିତ କରନ୍ତୁ"},
    "mark_followup_complete_suffix": {"en": "complete", "hi": "पूर्ण", "or": "ସମ୍ପୂର୍ଣ୍ଣ"},
    "record_label": {"en": "Record", "hi": "रिकॉर्ड", "or": "ରେକର୍ଡ"},
    "created_label": {"en": "Created", "hi": "बनाया गया", "or": "ସୃଷ୍ଟି ହୋଇଛି"},
    "last_updated_label": {"en": "Last updated", "hi": "अंतिम अद्यतन", "or": "ଶେଷ ଅଦ୍ୟତନ"},
    "reviewed_at_label": {"en": "Reviewed at", "hi": "समीक्षा की गई", "or": "ସମୀକ୍ଷା ହୋଇଛି"},
    "consent_recorded_label": {"en": "Consent recorded", "hi": "सहमति दर्ज", "or": "ସମ୍ମତି ଲିପିବଦ୍ଧ"},
    "not_recorded": {"en": "not recorded", "hi": "दर्ज नहीं", "or": "ଲିପିବଦ୍ଧ ହୋଇନାହିଁ"},
    "additional_ai_questions": {
        "en": "Additional AI-suggested questions (review before use):",
        "hi": "अतिरिक्त एआई-सुझाए गए प्रश्न (उपयोग से पहले समीक्षा करें):",
        "or": "ଅତିରିକ୍ତ AI-ପରାମର୍ଶିତ ପ୍ରଶ୍ନ (ବ୍ୟବହାର ପୂର୍ବରୁ ସମୀକ୍ଷା କରନ୍ତୁ):",
    },
    "safety_net_summary": {
        "en": "\U0001f6e1️ Rules-based safety-net cross-check (click to expand)",
        "hi": "\U0001f6e1️ नियम-आधारित सुरक्षा-जाल क्रॉस-चेक (विस्तार हेतु क्लिक करें)",
        "or": "\U0001f6e1️ ନିୟମ-ଆଧାରିତ ସୁରକ୍ଷା-ଜାଲ କ୍ରସ୍-ଚେକ୍ (ବିସ୍ତାର ପାଇଁ କ୍ଲିକ୍ କରନ୍ତୁ)",
    },
    "safety_net_body_prefix": {
        "en": "The deterministic rules engine independently read the same raw text and would, on its own, have assigned:",
        "hi": "नियतात्मक नियम इंजन ने स्वतंत्र रूप से वही कच्चा पाठ पढ़ा और अपने आप निम्न प्राथमिकता दी होती:",
        "or": "ନିର୍ଣ୍ଣୟାତ୍ମକ ନିୟମ ଇଞ୍ଜିନ୍ ସ୍ୱାଧୀନ ଭାବେ ସେହି କଞ୍ଚା ପାଠ୍ୟ ପଢ଼ି ନିଜେ ନିମ୍ନ ଅଗ୍ରାଧିକାର ଦେଇଥାନ୍ତା:",
    },
    "safety_net_body_suffix": {
        "en": "The final priority above is computed by that same rules engine, run on the combined set of everything both the AI and the rules engine detected - so it can only match or exceed this, never fall below it.",
        "hi": "उपरोक्त अंतिम प्राथमिकता उसी नियम इंजन द्वारा, एआई और नियम इंजन दोनों द्वारा पहचानी गई हर चीज़ के संयुक्त सेट पर चलाकर, निकाली जाती है - इसलिए यह इससे कम कभी नहीं, केवल बराबर या अधिक हो सकती है।",
        "or": "ଉପରୋକ୍ତ ଅନ୍ତିମ ଅଗ୍ରାଧିକାର ସେହି ସମାନ ନିୟମ ଇଞ୍ଜିନ୍ ଦ୍ୱାରା, AI ଏବଂ ନିୟମ ଇଞ୍ଜିନ୍ ଉଭୟ ଚିହ୍ନଟ କରିଥିବା ସବୁକିଛିର ମିଳିତ ସେଟ୍ ଉପରେ ଚଳାଇ, ହିସାବ କରାଯାଏ - ତେଣୁ ଏହା ଏଥିରୁ କେବେ କମ୍ ହୋଇପାରିବ ନାହିଁ, କେବଳ ସମାନ କିମ୍ବା ଅଧିକ ହୋଇପାରିବ।",
    },
    "rules_engine_detected_label": {"en": "Rules engine detected:", "hi": "नियम इंजन द्वारा पहचाना गया:", "or": "ନିୟମ ଇଞ୍ଜିନ୍ ଦ୍ୱାରା ଚିହ୍ନଟ ହୋଇଛି:"},
    # extractor.py's build_timeline() fixed literal shown when no duration could be parsed from
    # the raw text - was always shown in English on the Timeline section regardless of language.
    "duration_not_specified": {"en": "duration not specified", "hi": "अवधि निर्दिष्ट नहीं", "or": "ଅବଧି ଉଲ୍ଲେଖ ହୋଇନାହିଁ"},
}

# Risk-tier display label -> translated text (the badge at the very top of the triage detail
# page, and the rules-only cross-check tier) - previously always shown in English regardless of
# the selected language, arguably the single most visible untranslated element on the page.
RISK_TIER_TRANSLATIONS = {
    "emergency": {"en": "Emergency - See Immediately", "hi": "आपातकाल - तुरंत देखें", "or": "ଜରୁରୀକାଳୀନ - ତୁରନ୍ତ ଦେଖନ୍ତୁ"},
    "high": {"en": "High Priority", "hi": "उच्च प्राथमिकता", "or": "ଉଚ୍ଚ ଅଗ୍ରାଧିକାର"},
    "medium": {"en": "Medium Priority", "hi": "मध्यम प्राथमिकता", "or": "ମଧ୍ୟମ ଅଗ୍ରାଧିକାର"},
    "low": {"en": "Low Priority / Routine", "hi": "निम्न प्राथमिकता / नियमित", "or": "ନିମ୍ନ ଅଗ୍ରାଧିକାର / ନିୟମିତ"},
    "unclassified": {"en": "Unclassified", "hi": "अवर्गीकृत", "or": "ଅଶ୍ରେଣୀକୃତ"},
}

# Note status -> translated text (status dropdown options and the "Status: X" line at the top of
# the triage detail page).
STATUS_TRANSLATIONS = {
    "new": {"en": "New", "hi": "नया", "or": "ନୂଆ"},
    "in_review": {"en": "In review", "hi": "समीक्षाधीन", "or": "ସମୀକ୍ଷାଧୀନ"},
    "reviewed": {"en": "Reviewed", "hi": "समीक्षित", "or": "ସମୀକ୍ଷିତ"},
    "referred": {"en": "Referred", "hi": "रेफर किया गया", "or": "ରେଫର୍ କରାଯାଇଛି"},
    "closed": {"en": "Closed", "hi": "बंद", "or": "ବନ୍ଦ"},
}

# Canonical symptom name -> translated display label.
#
# COVERAGE NOTE (fixed as a real, confirmed gap): this dict originally covered only 7 of the
# 27 canonical symptoms in triage_engine/risk_rules.py's SYMPTOM_ONTOLOGY. Any of the other 20
# (seizure, rash, sore throat, etc.) fell through translate_symptom_label()'s English fallback
# and were shown in English even when the reviewer had selected Hindi or Odia - directly
# undermining a patient's Hindi/Odia voice input being reflected back as Hindi/Odia output on
# the review page. All 27 are now covered; the ODIA ACCURACY NOTE above still applies to every
# entry here, original 7 included.
SYMPTOM_TRANSLATIONS = {
    "chest_pain": {"en": "Chest pain", "hi": "सीने में दर्द", "or": "ଛାତି ଯନ୍ତ୍ରଣା"},
    "breathlessness": {"en": "Breathlessness", "hi": "सांस लेने में तकलीफ", "or": "ନିଶ୍ୱାସ କଷ୍ଟ"},
    "unconsciousness": {"en": "Unconsciousness", "hi": "बेहोशी", "or": "ଅଚେତନ ଅବସ୍ଥା"},
    "seizure": {"en": "Seizure", "hi": "दौरा (मिर्गी)", "or": "ଝଡ଼କା (ମୃଗୀ)"},
    "stroke_signs": {"en": "Signs of stroke", "hi": "लकवे (स्ट्रोक) के लक्षण", "or": "ପକ୍ଷାଘାତ (ଷ୍ଟ୍ରୋକ) ଲକ୍ଷଣ"},
    "severe_bleeding": {"en": "Severe bleeding", "hi": "गंभीर रक्तस्राव", "or": "ଗୁରୁତର ରକ୍ତସ୍ରାବ"},
    "blue_lips": {"en": "Blue lips", "hi": "होंठों का नीला पड़ना", "or": "ଓଠ ନୀଳ ପଡ଼ିବା"},
    "severe_abdominal_pain": {"en": "Severe abdominal pain", "hi": "पेट में तेज़ दर्द", "or": "ପେଟରେ ତୀବ୍ର ଯନ୍ତ୍ରଣା"},
    "high_fever": {"en": "Fever", "hi": "बुखार", "or": "ଜ୍ୱର"},
    "persistent_vomiting": {"en": "Persistent vomiting", "hi": "लगातार उल्टी", "or": "ବାରମ୍ବାର ବାନ୍ତି"},
    "diarrhea": {"en": "Diarrhea", "hi": "दस्त", "or": "ଝାଡ଼ା"},
    "dehydration_signs": {"en": "Signs of dehydration", "hi": "निर्जलीकरण के लक्षण", "or": "ଜଳଅଭାବ (ଡିହାଇଡ୍ରେସନ)ର ଲକ୍ଷଣ"},
    "cough": {"en": "Cough", "hi": "खांसी", "or": "କାଶ"},
    "headache": {"en": "Headache", "hi": "सिरदर्द", "or": "ମୁଣ୍ଡ ଯନ୍ତ୍ରଣା"},
    "severe_headache_sudden": {"en": "Sudden severe headache", "hi": "अचानक तेज़ सिरदर्द", "or": "ହଠାତ୍ ତୀବ୍ର ମୁଣ୍ଡ ଯନ୍ତ୍ରଣା"},
    "body_ache": {"en": "Body ache", "hi": "बदन दर्द", "or": "ଶରୀର ଯନ୍ତ୍ରଣା"},
    "rash": {"en": "Skin rash", "hi": "त्वचा पर चकत्ते", "or": "ଚମଡ଼ାରେ ଚକତା"},
    "fatigue": {"en": "Fatigue", "hi": "थकान", "or": "କ୍ଳାନ୍ତି"},
    "sore_throat": {"en": "Sore throat", "hi": "गले में खराश", "or": "ଗଳା ଯନ୍ତ୍ରଣା"},
    "burning_urination": {"en": "Burning urination", "hi": "पेशाब में जलन", "or": "ପରିସ୍ରାରେ ଜାଳାପୋଡ଼ା"},
    "pregnancy_bleeding": {"en": "Bleeding during pregnancy", "hi": "गर्भावस्था में रक्तस्राव", "or": "ଗର୍ଭାବସ୍ଥାରେ ରକ୍ତସ୍ରାବ"},
    "reduced_fetal_movement": {"en": "Reduced fetal movement", "hi": "गर्भ में शिशु की हलचल कम होना", "or": "ଗର୍ଭସ୍ଥ ଶିଶୁର ଗତିବିଧି କମିବା"},
    "infant_poor_feeding": {"en": "Infant feeding poorly", "hi": "शिशु का दूध ठीक से न पीना", "or": "ଶିଶୁ ଠିକ୍ ଭାବେ ଦୁଧ ନ ପିଇବା"},
    "injury_fracture": {"en": "Injury or suspected fracture", "hi": "चोट या हड्डी टूटना", "or": "ଆଘାତ କିମ୍ବା ହାଡ଼ ଭାଙ୍ଗିବା"},
    "chest_injury": {"en": "Chest injury", "hi": "छाती में चोट", "or": "ଛାତିରେ ଆଘାତ"},
    "mental_health_crisis": {"en": "Mental health crisis", "hi": "मानसिक स्वास्थ्य संकट", "or": "ମାନସିକ ସ୍ୱାସ୍ଥ୍ୟ ସଙ୍କଟ"},
    "occupational_exposure": {"en": "Workplace hazardous exposure", "hi": "कार्यस्थल पर हानिकारक पदार्थ के संपर्क में आना", "or": "କାର୍ଯ୍ୟସ୍ଥଳରେ କ୍ଷତିକାରକ ପଦାର୍ଥ ସଂସ୍ପର୍ଶ"},
}

# Symptom category code -> translated display label (used next to each reported symptom).
CATEGORY_TRANSLATIONS = {
    "cardiac": {"en": "Cardiac", "hi": "हृदय संबंधी", "or": "ହୃଦ‌ ସମ୍ବନ୍ଧୀୟ"},
    "respiratory": {"en": "Respiratory", "hi": "श्वसन संबंधी", "or": "ଶ୍ୱାସକ୍ରିୟା ସମ୍ବନ୍ଧୀୟ"},
    "neuro": {"en": "Neurological", "hi": "तंत्रिका तंत्र संबंधी", "or": "ସ୍ନାୟୁ ସମ୍ବନ୍ଧୀୟ"},
    "trauma": {"en": "Trauma/Injury", "hi": "चोट", "or": "ଆଘାତ"},
    "gi": {"en": "Gastrointestinal", "hi": "पेट/आंत संबंधी", "or": "ପେଟ/ଅନ୍ତନଳୀ ସମ୍ବନ୍ଧୀୟ"},
    "infection": {"en": "Infection", "hi": "संक्रमण", "or": "ସଂକ୍ରମଣ"},
    "derm": {"en": "Skin", "hi": "त्वचा संबंधी", "or": "ଚର୍ମ ସମ୍ବନ୍ଧୀୟ"},
    "ent": {"en": "Ear/Nose/Throat", "hi": "कान-नाक-गला", "or": "କାନ-ନାକ-ଗଳା"},
    "urinary": {"en": "Urinary", "hi": "मूत्र संबंधी", "or": "ପରିସ୍ରା ସମ୍ବନ୍ଧୀୟ"},
    "obstetric": {"en": "Obstetric", "hi": "प्रसूति संबंधी", "or": "ପ୍ରସୂତି ସମ୍ବନ୍ଧୀୟ"},
    "pediatric": {"en": "Pediatric", "hi": "शिशु/बाल रोग", "or": "ଶିଶୁ ରୋଗ"},
    "mental_health": {"en": "Mental health", "hi": "मानसिक स्वास्थ्य", "or": "ମାନସିକ ସ୍ୱାସ୍ଥ୍ୟ"},
    "occupational": {"en": "Occupational", "hi": "व्यावसायिक", "or": "ବୃତ୍ତିଗତ"},
    "general": {"en": "General", "hi": "सामान्य", "or": "ସାଧାରଣ"},
}

# Fixed follow-up question bank, English -> Hindi / Odia (best-effort demo phrasing).
#
# COVERAGE NOTE (fixed as a real, confirmed gap, same class as SYMPTOM_TRANSLATIONS above): this
# only covered 6 of the ~29 distinct follow-up-question strings extractor.py's
# CATEGORY_FOLLOWUPS/generate_follow_up_questions() can actually produce - every category besides
# cardiac/infection/the 3 generic ones fell through to raw English on the triage detail page even
# when Hindi/Odia was selected. All of them are now covered.
FOLLOWUP_TRANSLATIONS_HI = {
    "Does the pain radiate to the arm, jaw, or back?": "क्या दर्द बांह, जबड़े या पीठ तक फैलता है?",
    "Is there associated sweating, nausea, or breathlessness?": "क्या साथ में पसीना, जी मिचलाना या सांस फूलना है?",
    "Has the temperature been measured with a thermometer? What was the reading?": "क्या थर्मामीटर से तापमान मापा गया? रीडिंग क्या थी?",
    "What is the patient's exact age (or date of birth)?": "रोगी की सटीक आयु (या जन्मतिथि) क्या है?",
    "Exactly when did the symptoms start?": "लक्षण ठीक से कब शुरू हुए?",
    "Please record temperature, pulse, blood pressure, and SpO2 if a device is available.": "यदि उपकरण उपलब्ध हो तो तापमान, नब्ज, रक्तचाप और SpO2 दर्ज करें।",
    "Is there wheezing or noisy breathing?": "क्या सांस लेने में सीटी जैसी आवाज़ या घरघराहट है?",
    "Does breathlessness occur at rest or only on exertion?": "क्या सांस फूलना आराम करते समय होता है या केवल मेहनत करने पर?",
    "When exactly did the symptoms start, and did they come on suddenly?": "लक्षण ठीक से कब शुरू हुए, और क्या ये अचानक शुरू हुए?",
    "Is there any weakness, numbness, or trouble speaking?": "क्या कोई कमज़ोरी, सुन्नपन, या बोलने में परेशानी है?",
    "How many episodes in the last 24 hours?": "पिछले 24 घंटों में कितनी बार हुआ?",
    "Is there blood in vomit or stool?": "क्या उल्टी या मल में खून है?",
    "How many weeks pregnant is the patient?": "रोगी को कितने सप्ताह की गर्भावस्था है?",
    "Any history of complications in this or a previous pregnancy?": "क्या इस या पिछली गर्भावस्था में कोई जटिलता हुई थी?",
    "Is the child alert and responsive between episodes?": "क्या बच्चा एपिसोड के बीच सतर्क और प्रतिक्रियाशील है?",
    "How many wet diapers / urinations in the last 24 hours?": "पिछले 24 घंटों में कितनी बार पेशाब/गीला डायपर हुआ?",
    "How did the injury occur?": "चोट कैसे लगी?",
    "Can the affected area be moved normally?": "क्या प्रभावित हिस्से को सामान्य रूप से हिलाया जा सकता है?",
    "Any associated chills, rash, or localized pain?": "क्या साथ में ठंड लगना, चकत्ते, या स्थानीय दर्द है?",
    "Is the patient safe right now and not alone?": "क्या रोगी अभी सुरक्षित है और अकेला नहीं है?",
    "Escalate immediately to a qualified counselor / medical officer - do not rely on this tool for mental health crises.": "तुरंत किसी योग्य परामर्शदाता/चिकित्सा अधिकारी को सूचित करें - मानसिक स्वास्थ्य संकट के लिए इस उपकरण पर निर्भर न रहें।",
    "What substance or material was involved in the exposure?": "संपर्क में कौन सा पदार्थ या सामग्री शामिल थी?",
    "Was protective equipment being used at the time?": "क्या उस समय सुरक्षा उपकरण का उपयोग किया जा रहा था?",
    "Any other symptoms not yet mentioned?": "क्या कोई अन्य लक्षण हैं जिनका अभी तक ज़िक्र नहीं हुआ?",
    "Any known chronic conditions or ongoing medications?": "क्या कोई ज्ञात दीर्घकालिक बीमारी या चल रही दवाएं हैं?",
    "Is the rash spreading, and is there any associated fever?": "क्या चकत्ते फैल रहे हैं, और क्या साथ में बुखार है?",
    "Any fever, ear pain, or difficulty breathing along with the throat symptoms?": "क्या गले की समस्या के साथ बुखार, कान में दर्द, या सांस लेने में कठिनाई है?",
    "Any fever, back pain, or blood in urine?": "क्या बुखार, कमर दर्द, या पेशाब में खून है?",
    "Is there swelling, redness, or inability to bear weight?": "क्या सूजन, लालिमा, या वज़न सहन न कर पाने की समस्या है?",
}

FOLLOWUP_TRANSLATIONS_OR = {
    "Does the pain radiate to the arm, jaw, or back?": "ଯନ୍ତ୍ରଣା ବାହୁ, ହନୁ କିମ୍ବା ପିଠିକୁ ବ୍ୟାପେ କି?",
    "Is there associated sweating, nausea, or breathlessness?": "ସାଙ୍ଗକୁ ଝାଳ, ବାନ୍ତି ଭାବ କିମ୍ବା ନିଶ୍ୱାସ କଷ୍ଟ ଅଛି କି?",
    "Has the temperature been measured with a thermometer? What was the reading?": "ଥର୍ମୋମିଟର ସାହାଯ୍ୟରେ ତାପମାତ୍ରା ମପାଯାଇଛି କି? ରିଡିଂ କେତେ ଥିଲା?",
    "What is the patient's exact age (or date of birth)?": "ରୋଗୀଙ୍କର ସଠିକ୍ ବୟସ (କିମ୍ବା ଜନ୍ମ ତାରିଖ) କେତେ?",
    "Exactly when did the symptoms start?": "ଲକ୍ଷଣଗୁଡ଼ିକ ଠିକ୍ କେବେ ଆରମ୍ଭ ହୋଇଥିଲା?",
    "Please record temperature, pulse, blood pressure, and SpO2 if a device is available.": "ଯଦି ଉପକରଣ ଉପଲବ୍ଧ ଥାଏ, ତାପମାତ୍ରା, ନାଡ଼ି, ରକ୍ତଚାପ ଏବଂ SpO2 ଲେଖି ରଖନ୍ତୁ।",
    "Is there wheezing or noisy breathing?": "ନିଶ୍ୱାସ ନେବାରେ ସିଟି ପରି ଶବ୍ଦ କିମ୍ବା ଘଡ଼ଘଡ଼ ଅଛି କି?",
    "Does breathlessness occur at rest or only on exertion?": "ନିଶ୍ୱାସ କଷ୍ଟ ବିଶ୍ରାମ ସମୟରେ ହୁଏ ନା କେବଳ ପରିଶ୍ରମ କଲାବେଳେ?",
    "When exactly did the symptoms start, and did they come on suddenly?": "ଲକ୍ଷଣଗୁଡ଼ିକ ଠିକ୍ କେବେ ଆରମ୍ଭ ହୋଇଥିଲା, ଏବଂ ଏହା ହଠାତ୍ ଆରମ୍ଭ ହୋଇଥିଲା କି?",
    "Is there any weakness, numbness, or trouble speaking?": "କୌଣସି ଦୁର୍ବଳତା, ଝାଣ୍ଡିମାଡ଼ି, କିମ୍ବା କଥା କହିବାରେ ଅସୁବିଧା ଅଛି କି?",
    "How many episodes in the last 24 hours?": "ଗତ 24 ଘଣ୍ଟାରେ କେତେ ଥର ହୋଇଛି?",
    "Is there blood in vomit or stool?": "ବାନ୍ତି କିମ୍ବା ମଳରେ ରକ୍ତ ଅଛି କି?",
    "How many weeks pregnant is the patient?": "ରୋଗୀ କେତେ ସପ୍ତାହର ଗର୍ଭବତୀ?",
    "Any history of complications in this or a previous pregnancy?": "ଏହି କିମ୍ବା ପୂର୍ବ ଗର୍ଭାବସ୍ଥାରେ କୌଣସି ଜଟିଳତାର ଇତିହାସ ଅଛି କି?",
    "Is the child alert and responsive between episodes?": "ଏପିସୋଡ୍ ମଧ୍ୟରେ ଶିଶୁ ସତର୍କ ଏବଂ ପ୍ରତିକ୍ରିୟାଶୀଳ ଅଛି କି?",
    "How many wet diapers / urinations in the last 24 hours?": "ଗତ 24 ଘଣ୍ଟାରେ କେତେ ଥର ପରିସ୍ରା/ଓଦା ଡାଏପର ହୋଇଛି?",
    "How did the injury occur?": "ଆଘାତ କିପରି ହୋଇଥିଲା?",
    "Can the affected area be moved normally?": "ପ୍ରଭାବିତ ଅଂଶକୁ ସାଧାରଣ ଭାବେ ଘୁଞ୍ଚାଇ ହେଉଛି କି?",
    "Any associated chills, rash, or localized pain?": "ସାଙ୍ଗକୁ ଥଣ୍ଡା ଲାଗିବା, ଚକତା, କିମ୍ବା ସ୍ଥାନୀୟ ଯନ୍ତ୍ରଣା ଅଛି କି?",
    "Is the patient safe right now and not alone?": "ରୋଗୀ ବର୍ତ୍ତମାନ ସୁରକ୍ଷିତ ଏବଂ ଏକୁଟିଆ ନାହାନ୍ତି କି?",
    "Escalate immediately to a qualified counselor / medical officer - do not rely on this tool for mental health crises.": "ତୁରନ୍ତ ଯୋଗ୍ୟ ପରାମର୍ଶଦାତା/ଚିକିତ୍ସା ଅଧିକାରୀଙ୍କୁ ଜଣାନ୍ତୁ - ମାନସିକ ସ୍ୱାସ୍ଥ୍ୟ ସଙ୍କଟ ପାଇଁ ଏହି ଉପକରଣ ଉପରେ ନିର୍ଭର କରନ୍ତୁ ନାହିଁ।",
    "What substance or material was involved in the exposure?": "ସଂସ୍ପର୍ଶରେ କେଉଁ ପଦାର୍ଥ କିମ୍ବା ସାମଗ୍ରୀ ସାମିଲ ଥିଲା?",
    "Was protective equipment being used at the time?": "ସେହି ସମୟରେ ସୁରକ୍ଷା ଉପକରଣ ବ୍ୟବହାର ହେଉଥିଲା କି?",
    "Any other symptoms not yet mentioned?": "ଏପର୍ଯ୍ୟନ୍ତ ଉଲ୍ଲେଖ ହୋଇନଥିବା ଅନ୍ୟ କୌଣସି ଲକ୍ଷଣ ଅଛି କି?",
    "Any known chronic conditions or ongoing medications?": "କୌଣସି ଜଣା ଦୀର୍ଘସ୍ଥାୟୀ ରୋଗ କିମ୍ବା ଚାଲୁଥିବା ଔଷଧ ଅଛି କି?",
    "Is the rash spreading, and is there any associated fever?": "ଚକତା ବ୍ୟାପୁଛି କି, ଏବଂ ସାଙ୍ଗକୁ ଜ୍ୱର ଅଛି କି?",
    "Any fever, ear pain, or difficulty breathing along with the throat symptoms?": "ଗଳା ସମସ୍ୟା ସହିତ ଜ୍ୱର, କାନ ଯନ୍ତ୍ରଣା, କିମ୍ବା ନିଶ୍ୱାସ ନେବାରେ ଅସୁବିଧା ଅଛି କି?",
    "Any fever, back pain, or blood in urine?": "ଜ୍ୱର, ପିଠି ଯନ୍ତ୍ରଣା, କିମ୍ବା ପରିସ୍ରାରେ ରକ୍ତ ଅଛି କି?",
    "Is there swelling, redness, or inability to bear weight?": "ସୁଜା, ଲାଲିମା, କିମ୍ବା ଓଜନ ସହିବାରେ ଅସମର୍ଥତା ଅଛି କି?",
}


def get_ui_string(key, lang="en"):
    entry = UI_STRINGS.get(key, {})
    return entry.get(lang) or entry.get("en") or key


def translate_symptom_label(canonical, lang="en"):
    entry = SYMPTOM_TRANSLATIONS.get(canonical, {})
    fallback = canonical.replace("_", " ").capitalize()
    return entry.get(lang) or entry.get("en") or fallback


def translate_category_label(category, lang="en"):
    entry = CATEGORY_TRANSLATIONS.get(category, {})
    fallback = (category or "").replace("_", " ").capitalize()
    return entry.get(lang) or entry.get("en") or fallback


def translate_tier_label(tier, lang="en"):
    entry = RISK_TIER_TRANSLATIONS.get(tier, {})
    fallback = (tier or "").replace("_", " ").capitalize()
    return entry.get(lang) or entry.get("en") or fallback


def translate_status_label(status, lang="en"):
    entry = STATUS_TRANSLATIONS.get(status, {})
    fallback = (status or "").replace("_", " ").capitalize()
    return entry.get(lang) or entry.get("en") or fallback


def translate_followup_question(question, lang="en"):
    if lang == "hi":
        return FOLLOWUP_TRANSLATIONS_HI.get(question, question)
    if lang == "or":
        return FOLLOWUP_TRANSLATIONS_OR.get(question, question)
    return question


def translate_note_summary(structured_note, lang="en"):
    """Produce a lang-labelled, reviewer-facing rendering of the symptom
    list and follow-up questions. Free-text (raw_symptom_text) is NOT
    machine-translated by this lightweight module and is shown as
    originally entered, with a note to the reviewer.
    """
    note = None
    if lang in ("hi", "or"):
        note = ("Phrase-bank translation for demo purposes - spot-check against a native speaker "
                "before real-world use. The original raw patient text and OCR'd document text are "
                "always shown in the original language for reviewer accuracy; every other "
                "AI-generated field on this page (summary, chief complaint, missing info, extra "
                "follow-ups, and the photo description/findings if present) is separately "
                "translated on demand when a translation model is available, cached per note.")
    return {
        "lang": lang,
        "lang_label": SUPPORTED_LANGUAGES.get(lang, lang),
        "symptoms": [translate_symptom_label(s["canonical"], lang) for s in structured_note.get("symptoms", [])],
        "follow_up_questions": [translate_followup_question(q, lang) for q in structured_note.get("follow_up_questions", [])],
        "note": note,
    }
